Kuadrant/limitador-operator

- .github/workflows/go.yml
- Makefile
For now it just runs "make test". After fixing the build of the docker image we could add other targets to make sure that the image can be built and deployed to kubernetes.
> Add Github action that runs the tests

- config/manager/kustomization.yaml
- config/rbac/role.yaml
- controllers/limitador_controller.go
Adds RBAC permissions needed to run the operator in Kubernetes as suggested by @miguelsorianod in https://github.com/3scale-labs/limitador-operator/pull/2#discussion_r553858244
> Add RBAC permissions for Limitador controller

- Makefile
- controllers/limitador_controller.go
- controllers/limitador_controller_test.go
- pkg/limitador/k8s_objects.go
So the deployment and the service are deleted automatically when a
Limitador object is deleted.
* Fix limitador service namespace, which was harcoded to `default`
* Fix tests: Removing `Deleting a Limitador object` because the test context does not support garbage collection [link](https://book.kubebuilder.io/reference/envtest.html#testing-considerations)
> controllers/limitador: use owner refs

- .github/workflows/go.yml
- Makefile
- config/deploy/manfiests.yaml
- config/install/kustomization.yaml
- config/install/manifests.yaml
This PR tries to address Issue #16 to provide manifest files for situations where cloning the whole operator repo is not necessary.
> manifest files for easy prototyping

- .github/workflows/build-images.yaml
- .github/workflows/go.yml
- Makefile
- bundle/manifests/limitador-operator.clusterserviceversion.yaml
Adds a GitHub action triggered on branch/tag creation that builds and pushes the operator, bundle and index images.
Set VERSION to 0.2.0 (Last released version)
Pushed this branch to the kuadrant org rather than a fork to test https://github.com/Kuadrant/limitador-operator/actions/runs/1790008944
> Add image build GH action

- bundle/manifests/limitador-operator.clusterserviceversion.yaml
- config/deploy/manfiests.yaml
- config/install/manifests.yaml
- config/rbac/role.yaml
- config/samples/limitador_v1alpha1_limitador.yaml
- controllers/limitador_controller.go
- controllers/limitador_controller_test.go
- go.mod
- pkg/limitador/k8s_objects.go
- pkg/limitador/k8s_objects_test.go
- pkg/reconcilers/base_reconciler.go
Closes https://github.com/Kuadrant/limitador-operator/issues/27
This PR introduces the `ConfigMap` that holds the _state_ and _limits_ (configuration needed for setting up _Limitador_) which it's reconciled by the _limitador-controller_
The `ConfigMap` looks like:
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
labels:
app: limitador
name: limits-config-limitador-1 # Name constructed from "limits-config-" prefix and the `Limitador` CR name
data:
hash: 32trgresg3ydsagas # hash built from the actual limits. Used for reconciling (state)
limitador-config.yaml: |
limits:
- conditions: ["get-toy == yes"]
max_value: 2
namespace: toystore-app
seconds: 30
variables: []
- conditions:
- "admin == yes"
max_value: 2
namespace: toystore-app
seconds: 30
variables: []
- conditions: ["vhaction == yes"] …
```
> Reconciling limits `ConfigMap`

- bundle/manifests/limitador-operator-manager-config_v1_configmap.yaml
- bundle/manifests/limitador-operator.clusterserviceversion.yaml
- config/default/kustomization.yaml
- config/default/manager_metrics_patch.yaml
- config/deploy/manfiests.yaml
- config/install/manifests.yaml
- config/manager/controller_manager_config.yaml
- config/manager/kustomization.yaml
- config/manager/metrics_service.yaml
- config/prometheus/monitor.yaml
- config/rbac/kustomization.yaml
Remove the kube-rbac-proxy container from the controller-manager
https://github.com/Kuadrant/kuadrant-operator/pull/7#discussion_r797439423
See:
https://github.com/3scale/3scale-operator/pull/692
https://github.com/3scale-ops/prometheus-exporter-operator/pull/26
* deploy limitador locally
```
```
* Expose metrics service locally
```
kubectl port-forward --namespace limitador-operator-system service/limitador-operator-controller-manager-metrics-service 8080:8080
```
```
$ curl http://127.0.0.1:8080/metrics
controller_runtime_active_workers{controller="limitador"} 0
controller_runtime_max_concurrent_reconciles{controller="limitador"} 1
controller_runtime_reconcile_errors_total{controller="limitador"} 0
....
```
> remove kube-rbac-proxy sidecar

- controllers/limitador_controller.go
- controllers/limitador_controller_test.go
- pkg/limitador/k8s_objects.go
- pkg/limitador/k8s_objects_test.go
This PR enhance the `Limitador.Status` reconciling process, instead of requeueing every time it checks the status is not ready, now it will just watch the owned `Deployment` obj, and update its `Limitador.Status` once the deployment has changed its and it has enough `ReadyReplicas`.
It also fixes the Limitador Service Name generation and error reporting when it's instance is not found, or raised an error.
Closes https://github.com/Kuadrant/limitador-operator/issues/35
*Verification Steps:*
1. Lunch the cluster setup with 
```bash
```
2. When ready, create a new namespace:
```bash
kubectl create namespace "limitador-test"
```
3. Then, apply the following Limitador CR:
```bash
k -n limitador-test apply -f - <<EOF …
```
> Enhance status reconciling cycle

- api/v1alpha1/groupversion_info.go
- controllers/limitador_controller.go
- controllers/limitador_controller_test.go
- controllers/suite_test.go
- pkg/limitador/k8s_objects_test.go
- pkg/reconcilers/base_reconciler.go
* little fix in status reconcile. Avoid returning errors when limitador was not ready and  status did not change. Wait for a new reconciliation loop when the deployment object changes
* lint issues fixed
> little fix in status reconcile

- bundle/manifests/limitador-operator.clusterserviceversion.yaml
- config/deploy/manfiests.yaml
- config/manager/manager.yaml
- pkg/limitador/image.go
- pkg/limitador/image_test.go
- pkg/limitador/k8s_objects.go
- pkg/limitador/k8s_objects_test.go
Limitador image can be read from `RELATED_IMAGE_LIMITADOR` env var. Defaults to `quay.io/3scale/limitador:latest`-
Required to specify the limitador image from the CSV manifest
`spec.version` will override any value from `RELATED_IMAGE_LIMITADOR`.
The limitador image order of preference is:
* `spec.version` value (only allows tag, repo will alway be `quay.io/3scale/limitador`
* value from `RELATED_IMAGE_LIMITADOR` env var. Image repo and tag needs to be specified. For example: `quay.io/3scale/limitador:0.5.1`
* Default value: `quay.io/3scale/limitador:latest`
run cluster
```
make local-setup-kind
```
install CRDs
```
make install
```
run operator locally with specific `RELATED_IMAGE_LIMITADOR` env var.
```
RELATED_IMAGE_LIMITADOR=quay.io/3scale/limitador:0.5.1 make run
```
Create …
> limitador version from env var

- controllers/limitador_controller.go
- controllers/limitador_controller_test.go
- pkg/limitador/k8s_objects.go
- pkg/limitador/k8s_objects_test.go
* Limits config map reconciliation was based on a hash computed from a yaml serialized string. This PR change the approach to `reflect.DeepEqual` comparing method. The hash computation is sensitive to the order of the limit object keys (`variables`, `conditions`, `max_value`, ...). `reflect.DeepEqual` is not sensible when checking maps equality. Both of approaches are sensitive to the order of the list objects, and that is still a small enhancement to be done. 
* In controller test, have a better sync of updated objects from the controller. The test will check object's fields when it is for sure they have been updated by the controller.
run cluster
```
```
deploy limitador object
```
k apply -f config/samples/limitador_v1alpha1_limitador.yaml
```
Update limitador limits. …
> fix configmap reconciliation

- bundle/manifests/limitador-operator.clusterserviceversion.yaml
- config/deploy/manfiests.yaml
- config/manager/manager.yaml
Increase controller resource to 
* Limits
* cpu: 200m
* mem: 300 MB
* Requests:
* cpu: 200m
* mem: 200MB
I hit OOM issues when deployed the operator in Openshift. In k8s no OOM issues, though.
> increase controller resources

- Makefile
- bundle/manifests/limitador-operator.clusterserviceversion.yaml
- config/manifests/bases/limitador-operator.clusterserviceversion.template.yaml
- config/manifests/bases/limitador-operator.clusterserviceversion.yaml
This PR makes it possible to automate the generation of the ClusterServiceVersion image, bundle version and its tag. It also updates the maintainers list. Same as https://github.com/Kuadrant/kuadrant-operator/pull/37 and https://github.com/Kuadrant/authorino-operator/pull/93
> Automate CSV generation

- controllers/limitador_controller.go
- pkg/limitador/k8s_objects.go
* Change owner references to *controller owner references*. Basically enables to watch to changes when owned by some limitador CR. 
not controller owner references:
```yaml
ownerReferences:
- apiVersion: limitador.kuadrant.io/v1alpha1
name: limitador-sample
uid: 4a75619c-24c7-4f86-a48d-933fa9db97fb
```
controller owner references:
```yaml
ownerReferences:
- apiVersion: limitador.kuadrant.io/v1alpha1
blockOwnerDeletion: true
controller: true
name: limitador-sample
uid: 8d8b37c8-fc43-49f2-a1b6-570c52536ff4
```
* Add controller owner references to configmaps
* Add watch on owned configmaps. If externally the config map is changed, the operator will reconcile back to the desired state.
dev setup
```
```
Deploy the limitador CR
```yaml
k apply …
```
> Fix owner reference type

- controllers/limitador_controller.go
- pkg/reconcilers/deployment.go
Currently, when replicas are not set in the Limitador CR, the operator will enforce the replicas in the deployment object to 1. On each reconcilliation loop, the operator makes sure the replica value at the deployment matches the one specified in the CR.
The problem is that if the replica count is managed by some external controller (for example the HPA controller), the operator does not allow it and tries to update deployment's replica count with the one in the CR.
This PR enables the control over the replica by the limitador operator, **only** when it is specified in the Limitador CR. If it is not specified in the CR, the operator will not reconcile the replicas allowing other controller do so. 
Reconciliation (implemented by the mutator) only added when the replicas field is set.
dev …
> Replica reconciliation

- controllers/limitador_controller.go
If the limits config map, for whatever reason, does not have a valid content to be parsed into a limits array, the operator fails to reconcile and cannot recover. This fix, is to handle that error. So if a invalid content is found, revert to desired content.
dev setup
```
```
Deploy the limitador CR
```yaml
k apply -f - <<EOF
---
metadata:
name: limitador-sample
spec:
limits:
- conditions: ["get_toy == 'yes'"]
max_value: 2
namespace: toystore-app
seconds: 30
variables: []
EOF
```
Check that the limits config map content
```yaml
k get configmaps limits-config-limitador-sample -o jsonpath='{.data}' | yq e -P
limitador-config.yaml: |
- conditions:
- get_toy == 'yes'
max_value: 2
namespace: toystore-app
seconds: 30 …
```
> support invalid limits configmap

- api/v1alpha1/limitador_types.go
Fix redis-cached deployment when no options are set.
It was panic-ing when the spec was
```yaml
metadata:
name: limitador
spec:
storage:
redis-cached:
configSecretRef:
name: redisconfig
```
```
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1381d23]
goroutine 312 [running]:
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile.func1()
/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.2/pkg/internal/controller/controller.go:118 +0x1f4
panic({0x14f07c0, 0x2373ad0})
/usr/local/go/src/runtime/panic.go:838 +0x207 …
```
> fix redis-cached deployment when no options are set

- Makefile
First I fixed the "is_version_semantic" shell script which was never working in bash.  
Then I realized that the bundle changed with image pointing to ''v0.0.0". Then, I removed setting IMAGE_TAG based on "is_version_semantic". 
* setting version to "1.2.3"
```
$ make bundle VERSION=1.2.3
/home/eguzki/git/kuadrant/limitador-operator2/bin/controller-gen rbac:roleName=manager-role crd webhook paths="./..." output:crd:artifacts:config=config/crd/bases
/home/eguzki/git/kuadrant/limitador-operator2/bin/operator-sdk generate kustomize manifests -q
WARN[0000] Skipping definitions parsing for API {}: Go type not found 
cd config/manager && /home/eguzki/git/kuadrant/limitador-operator2/bin/kustomize edit set image controller=quay.io/kuadrant/limitador-operator:v1.2.3
V="limitador-operator.v1.2.3" …
```
> fix Makefile version is semantic check

- README.md
- api/v1alpha1/limitador_types.go
- api/v1alpha1/zz_generated.deepcopy.go
- bundle/manifests/limitador.kuadrant.io_limitadors.yaml
- config/crd/bases/limitador.kuadrant.io_limitadors.yaml
- controllers/limitador_controller.go
- controllers/limitador_controller_test.go
- doc/rate-limit-headers.md
- doc/storage.md
- pkg/limitador/k8s_objects.go
- pkg/limitador/k8s_objects_test.go
- pkg/reconcilers/deployment.go
Exposes the rate limit headers feature implemented in limitador https://github.com/Kuadrant/limitador/pull/158/files
```yaml
metadata:
name: limitador-sample
spec:
rateLimitHeaders: DRAFT_VERSION_03
```
Current valid values are: 
* *DRAFT_VERSION_03* (ref: https://datatracker.ietf.org/doc/id/draft-polli-ratelimit-headers-03.html)
* *NONE*
By default, i.e. with the simplest limitador CR, `--rate-limit-headers` command line arg is not included in the limitador's deployment.
Reconciliation of `spec.rateLimitHeaders`, meaning that changing (patching) that field `spec.rateLimitHeaders` after being created will trigger rolling out of the limitador deployment.
TODO
* Dev setup
```
```
* Limitador CR without rate limit …
> Add Rate limit headers to the Limitador CRD

- .github/workflows/build-images-base.yaml
- .github/workflows/build-images-scheduled.yaml
- Makefile
- doc/development.md
This PR introduces the following changes:
1. Adds the version of limitador in the operator bundle
2. Modifies the Github workflow to build both catalog and bundle with the same limitador version
3. Introduces the scheduled build for sha images
4. Updates the documentation
> Limitador version in bundle

- Makefile
- doc/development.md
- utils/kind-cluster.yaml
Similar to https://github.com/Kuadrant/kuadrant-operator/pull/209, bumping kind version to v0.20.0 and image to kindest/node:v1.27.3 to allow running `make local-setup` on Darwin arm64 using `cgroupv2` on docker
> kind: bump to v0.20.0 & pin image to kindest/node:v1.27.3

- .gitignore
* Ignore vendor directory since it's not specifically committed anyhow. This prevents a contributor from accidently commiting it if generated by them
> ignore: vendor directory

- .github/workflows/test.yaml
- README.md
* Adds codecov to test workflow
Closes: https://github.com/Kuadrant/limitador-operator/issues/69
> workflow: add codecov

- README.md
- doc/development.md
- doc/logging.md
- doc/storage.md
- pkg/limitador/image_test.go
* Fix broken doc referecencs
* Use relative doc links for consistency
* Also allows Goland IDE to find the docs in the rendered markdown 
* Fix typo
* General formatting fixes for yaml & tables
> docs: minor improvements

- .github/workflows/build-images-base.yaml
- .github/workflows/test.yaml
- Dockerfile
- doc/development.md
- go.mod
* Use go1.19 to align with most other kuadrant projects
* Use actions/checkout@v3 instead
* Use actions/setup-go@v4 instead
Closes: https://github.com/Kuadrant/limitador-operator/issues/84 https://github.com/Kuadrant/limitador-operator/issues/85
> Go1.19 & actions/checkout@v3 & actions/setup-go@v4

- controllers/limitador_controller.go
- controllers/limitador_controller_test.go
- pkg/reconcilers/deployment.go
- pkg/reconcilers/deployment_test.go
- pkg/reconcilers/suite_test.go
Ensure that only containers that are managed by the limitador-operator can be added to the limitador deployment CR.
* Run this branch
```sh
```
* Add a limitador deployment
```sh
echo "
metadata:
name: limitador-sample
spec:
listener:
http:
port: 8080
grpc:
port: 8081
limits:
- conditions: ["get_toy == 'yes'"]
max_value: 2
namespace: toystore-app
seconds: 30
variables: []
" | kubectl apply -f -
```
* **Check:** There should only be one container in the deployment spec
```sh
kubectl get deployment limitador-sample -o jsonpath='{.spec.template.spec.containers}' | jq 'length'
```
* Add new container to the deployment CR
```sh
kubectl patch deployment limitador-sample -n default --type='json' -p='[{"op": "add", …
```
> deployment CR reconcile of containers

- .github/workflows/build-images-base.yaml
- make/catalog.mk
- utils/generate-catalog.sh
This PR is part of Kuadrant Operator issue https://github.com/Kuadrant/kuadrant-operator/issues/244
The workflow dispatch input channels accepts comma separated values, i.e.: "stable,release". The Makefile target could be executed as:
```sh
make bundle \
REGISTRY=quay.io \
ORG=kuadrant \
VERSION=0.5.0 \
IMAGE_TAG=v0.5.0 \
LIMITADOR_VERSION=1.2.0 \
CHANNELS=stable,release
```
And it will generate, among other changes, the following:
```sh
diff --git a/bundle.Dockerfile b/bundle.Dockerfile
index f229f85..bff38ce 100644
--- a/bundle.Dockerfile
+++ b/bundle.Dockerfile
@@ -5,8 +5,8 @@ LABEL operators.operatorframework.io.bundle.mediatype.v1=registry+v1
-LABEL operators.operatorframework.io.bundle.channels.v1=alpha
+LABEL operators.operatorframework.io.bundle.channels.v1=stable,release
index …
```
> [workflow] Adding channels input for bundle creation

- README.md
Point people interested to reach out to the [#kuadrant](https://kubernetes.slack.com/archives/C05J0D0V525) channel in the Kubernetes Slack workspace.
> doc: #kuadrant channel on kubernetes.slack.com

- .github/workflows/build-images-base.yaml
- Makefile
- bundle/manifests/limitador-operator.clusterserviceversion.yaml
- config/manifests/bases/limitador-operator.clusterserviceversion.yaml
- doc/development.md
- make/catalog.mk
- utils/generate-catalog.sh
This PR fixes the discrepancy between the bundle replaces value  provided to OperatorHub (by hand) and our bundle and catalog images (missing until now). It aims to fix the failing tests in  both https://github.com/k8s-operatorhub/community-operators/actions/runs/6323398403/job/17171016267?pr=3298 and https://github.com/redhat-openshift-ecosystem/community-operators-prod/actions/runs/6323474102/job/17171305652?pr=3350 . 
Notes:
A re-release needs to be done... either using this mod or by hand including the replaces in the catalog and bundle.
> Build images with replaces operator image

- .github/codecov.yaml
Added [Codecov Status Check](https://docs.codecov.com/docs/commit-status) target and threshold
`target` is the minimum coverage ratio that the commit must meet to be considered a success.
`threshold` allows the coverage to drop by X%, and posting a success status.
```
❯ cat .github/codecov.yaml | curl --data-binary @- https://codecov.io/validate
Valid!
```
> codecov: add target and threshold

- api/v1alpha1/limitador_types.go
- bundle/manifests/limitador-operator.clusterserviceversion.yaml
- bundle/manifests/limitador.kuadrant.io_limitadors.yaml
- config/crd/bases/limitador.kuadrant.io_limitadors.yaml
- controllers/limitador_controller_test.go
- pkg/limitador/deployment_options.go
This builds on the changes in #112 - which lets a `RateLimit` have a name.
Add the `telemetry` field to the `LimitadorSpec`, which currently has two valid options: `basic` (what it's been so far) and `exhaustive`, which will result in starting the Limitador server process with the `--limit-name-in-labels` option, resulting in the two metrics, `limited_calls` & `authorized_calls`, to include the limit's name field as label - providing better metrics about what `Limit` is limiting or allow traffic through.
> Enable per limit metrics

- api/v1alpha1/limitador_types.go
- api/v1alpha1/zz_generated.deepcopy.go
- bundle/manifests/limitador-operator.clusterserviceversion.yaml
- bundle/manifests/limitador.kuadrant.io_limitadors.yaml
- config/crd/bases/limitador.kuadrant.io_limitadors.yaml
- controllers/limitador_controller.go
- controllers/limitador_controller_test.go
- doc/storage.md
- pkg/limitador/deployment_options.go
- pkg/limitador/k8s_objects.go
- pkg/limitador/redis_cache_storage_options.go
- pkg/limitador/redis_cache_storage_options_test.go
- pkg/limitador/redis_storage_options.go
- pkg/limitador/redis_storage_options_test.go
- pkg/reconcilers/deployment.go
- pkg/reconcilers/deployment_test.go
Closes: https://github.com/Kuadrant/limitador-operator/issues/106 
This change pass the Redis URL to the limitador-server as a Environment Variable in the deployment config.
Verification steps requires  Redis to be configured in the cluster so the running limitador does not have connection error logs.   
Set up the kind cluster with this deployment.
```
```
Create redis deployment, service and secret. The secret will be used in the limitador deployment and should be created in the same namespace. See changes in docs about this.
```sh
echo "
apiVersion: v1
kind: Secret
metadata:
name: redisconfig
stringData:
URL: redis://redis.default.svc.cluster.local/0
type: Opaque
---
apiVersion: v1
kind: Service
metadata:
name: redis
spec:
ports:
- port: 6379
protocol: TCP
targetPort: …
```
> Pass Redis URL as Env Var to Limitador deployment.

- api/v1alpha1/limitador_types.go
- bundle/manifests/limitador-operator.clusterserviceversion.yaml
- bundle/manifests/limitador.kuadrant.io_limitadors.yaml
- config/crd/bases/limitador.kuadrant.io_limitadors.yaml
- controllers/limitador_controller.go
- controllers/limitador_controller_affinity_test.go
- controllers/limitador_controller_limits_test.go
- controllers/limitador_controller_pdb_test.go
- controllers/limitador_controller_ports_test.go
- controllers/limitador_controller_replicas_test.go
- controllers/limitador_controller_resources_test.go
- controllers/limitador_controller_test.go
- controllers/limitador_controller_version_test.go
- controllers/limitador_status.go
- go.mod
- pkg/limitador/deployment_options.go
- pkg/limitador/deployment_options_test.go
- pkg/reconcilers/deployment.go
- pkg/reconcilers/service.go
Two main issues found:
* Limitador CR status check is not reading the right deployment name. Hence, the Limitador CR is never in `ready` state.
* Port configuration is not passed to the limitador process, only used to configure services and liveness probes. If default port is changed, the liveness probe tries a different port than the one limitador is listening on and thus, the deployment is never available.
Few minor issues found:
* Deployment ports not reconciled. If the ports are changed in the Limitador CR, the deployment is broken.
* Deployment liveness and readiness probes not reconciled. If the ports are changed in the Limitador CR, the deployment is broken.
* Service ports not reconciled. If the ports are changed in the Limitador CR, the traffic will not reach limitador.
* …
> fix status check

- Makefile
- bundle.Dockerfile
- bundle/manifests/limitador-operator.clusterserviceversion.yaml
- bundle/metadata/annotations.yaml
This PR fixes the https://github.com/operator-framework/operator-sdk/issues/6489 that was fixed in [v1.31.0](https://newreleases.io/project/github/operator-framework/operator-sdk/release/v1.31.0).
```sh
rm -rf bin
```
Setup a local cluster with OLM:
```sh
make kind-delete-cluster kind-create-cluster install-olm
```
The command does not return error. Additionally, check OLM is installed
```
k get csv packageserver -n olm 
```
Resulting in 
```
NAME            DISPLAY          VERSION   REPLACES   PHASE
packageserver   Package Server   0.27.0               Succeeded
```
> Upgrading operator-sdk to v1.32.0

- .github/workflows/test.yaml
- Makefile
- api/v1alpha1/limitador_types.go
- bundle/manifests/limitador-operator.clusterserviceversion.yaml
- config/rbac/role.yaml
- controllers/limitador_controller.go
- controllers/limitador_controller_affinity_test.go
- controllers/limitador_controller_limits_sync_test.go
- controllers/limitador_controller_limits_test.go
- controllers/limitador_controller_pdb_test.go
- controllers/limitador_controller_ports_test.go
- controllers/limitador_controller_replicas_test.go
- controllers/limitador_controller_resources_test.go
- controllers/limitador_controller_test.go
- controllers/limitador_controller_version_test.go
- doc/development.md
- go.mod
- go.sum
- pkg/limitador/deployment_options_test.go
- pkg/limitador/disk_storage_options_test.go
- pkg/limitador/k8s_objects.go
- pkg/limitador/k8s_objects_test.go
- utils/kind-cluster.yaml
Part of https://github.com/Kuadrant/kuadrant-operator/issues/414
This PR adds a feature to annotate Limitador pods with the limits config map resource version. This change ensures that modifications to the limits will promptly trigger a reload or synchronization of the limit configuration to Limitador pods. Consequently, it ensures that pod limits are always immediately up to date.
This enhancement will enable us to utilize the Limitador CR `Ready` condition as a way of naively assuming that limits are enforced.
Other additions include
* Updating kind to v0.22.0
* Refactor integration tests to use context to timeout tests and algin primarily use Gomega for assertions
The following have already been verified in the included integration test but if you want to verify manually:
* Checkout …
> feat: immediate limits sync to pod via annotation

- README.md
- api/v1alpha1/limitador_types.go
- bundle/manifests/limitador-operator.clusterserviceversion.yaml
- bundle/manifests/limitador.kuadrant.io_limitadors.yaml
- config/crd/bases/limitador.kuadrant.io_limitadors.yaml
- doc/tracing.md
- pkg/limitador/deployment_options.go
- pkg/limitador/deployment_options_test.go
A new `--tracing-endpoint` command was added to limitador in https://github.com/Kuadrant/limitador/pull/261. I have used a struct to match the spec in Authorino (eventually to contain an `Insecure` boolean once limitador supports TLS tracing endpoint).
`docker run --rm -t quay.io/kuadrant/limitador:latest limitador-server --help`
```sh
Rate Limiting Server
Usage: limitador-server [OPTIONS] <LIMITS_FILE> [STORAGE]
STORAGES:
memory        Counters are held in Limitador (ephemeral)
disk          Counters are held on disk (persistent)
redis         Uses Redis to store counters
redis_cached  Uses Redis to store counters, with an in-memory cache
Arguments:
<LIMITS_FILE>  The limit file to use
Options:
-b, --rls-ip <ip>
The IP to listen on for RLS [default: 0.0.0.0]
-p, --rls-port <port>
The …
```
> Add limitador tracing-endpoint command

- Makefile
- controllers/limitador_controller_affinity_test.go
- controllers/limitador_controller_limits_sync_test.go
- controllers/limitador_controller_limits_test.go
- controllers/limitador_controller_pdb_test.go
- controllers/limitador_controller_ports_test.go
- controllers/limitador_controller_replicas_test.go
- controllers/limitador_controller_resources_test.go
- controllers/limitador_controller_test.go
- controllers/limitador_controller_version_test.go
- controllers/suite_test.go
* Remove nodeTimeout from `BeforeEach` as the `SpecTimeout` includes the time used in `BeforeEach` 
* Run the integration tests in parrallel with some flags based on the recommendation at https://onsi.github.io/ginkgo/#recommended-continuous-integration-configuration
* Linux based runners looks to have 4 virtual CPU cored -  https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners#standard-github-hosted-runners-for-public-repositories
* 10 Parrallel process is an arbitary number that I've picked 
Locally the integration tests completes in ~1m40s (Pipeline can take longer overall ~ 4mins due to the workflow steps) (Previously takes ~11mins to complete when running sequentially)
> feat: run integration tests concurrently

- .github/workflows/release-helm-chart.yaml
- .gitignore
- Makefile
- charts/limitador-operator/.helmignore
- charts/limitador-operator/Chart.yaml
- charts/limitador-operator/templates/manifests.yaml
- charts/limitador-operator/values.yaml
- config/helm/kustomization.yaml
- make/helm.mk
This PR introduces a way to manage a Limitador Operator [Helm Chart](https://helm.sh/). This is not meant to replace the way we are building and delivering our manifests (Kustomize, OLM) but to provide an alternative (complementary) way of delivering the operator.
This early implementation uses Kustomize to create the chart template, instead of creating and maintaining new ones with Helm, to later customize the Helm only settings with its `values.yaml`
**NOTES**
* This chart (and every other operator chart we package in the future: Authorino, DNS, etc) bundles only the operator in the same fashion OLM does.
* The operator version matches the chart version
* This first release doesn't use helm templating, it provides only the manifests previously built by Kustomize.
* The sole repository …
> Hello helm

- .github/workflows/release-helm-chart.yaml
This PR fixes the path to the CI built chart package to be uploaded and removes unused input variables and redundant steps. This addresses too [this comment](https://github.com/Kuadrant/limitador-operator/pull/137#discussion_r1643074922) on the [PR introducing the workflow](https://github.com/Kuadrant/limitador-operator/pull/137).
> Helm Chart release workflow adjustments

- .github/workflows/build-images-base.yaml
- Dockerfile
- Makefile
- main.go
- utils/check-git-dirty.sh
- version/version.go
https://github.com/Kuadrant/authorino/issues/471
Added info log to display version, commit hash and whether the branch was dirty or not on build . 
Run `make build`  and `make local-setup` locally. Without any file changes made the hash should be displayed without appendixed `dirty` flag. Then add a comment to a file to have git detect new changes and re-run the commands checking binary and in-cluster for both respectively.
> added display version, hash and dirty in logs

- .github/workflows/build-images-base.yaml
- Makefile
- bundle.Dockerfile
- bundle/manifests/limitador-operator.clusterserviceversion.yaml
- bundle/metadata/annotations.yaml
- doc/development.md
- make/catalog.mk
- utils/generate-catalog.sh
* Adding the default channel to bundle annotations
* Custom catalog do not need multiple channels, only one. Taking the default channel as the one. In the future we could generate catalog with multiple channels and the bundle being member of all of those. But not use today.
> Missing info manifests

- bundle/manifests/limitador-operator.clusterserviceversion.yaml
- config/manifests/bases/limitador-operator.clusterserviceversion.yaml
Addressing warning from https://github.com/redhat-openshift-ecosystem/community-operators-prod/pull/5278#issuecomment-2389739278
> csv annotation description

- bundle/manifests/limitador-operator.clusterserviceversion.yaml
- config/manifests/bases/limitador-operator.clusterserviceversion.yaml
Addressing warning from https://github.com/redhat-openshift-ecosystem/community-operators-prod/pull/5278#issuecomment-2389739278
> Add description to owned customresources

- api/v1alpha1/limitador_types.go
- bundle/manifests/limitador-operator.clusterserviceversion.yaml
- bundle/manifests/limitador.kuadrant.io_limitadors.yaml
- charts/limitador-operator/templates/manifests.yaml
- config/crd/bases/limitador.kuadrant.io_limitadors.yaml
This PR adds new columns with status and age information to kubectl get output with -o wide option.
dev setup
```
```
```yaml
k apply -f - <<EOF
---
metadata:
name: limitador
spec: {}
EOF
```
Check Limitador columuns
```sh
kubectl get limitador -A -o wide
```
The expected output should contain `READY` and `AGE` columns
```
NAMESPACE   NAME        READY   AGE
default     limitador   True    52s
```
> Add CRDs printcolumns

- charts/limitador-operator/Chart.yaml
In order to be able to publish our Helm Charts in ArtifactHub.io and display valuable information in their repo site, we should provide some metadata described in https://artifacthub.io/docs/topics/annotations/helm/
> Preparing info for ArtifactHub.io

- .github/workflows/build-images-for-tag-release.yaml
This PR modifies the event listener for pushing tags following a GH action regex matching  semver with pre release and build metadata parts, like `vx.y.z-alpha1`, `vx.y.z-rc1`, `vx.y.z-dev`, etc. Previously it only matched `vx.y.z`
Following https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#filter-pattern-cheat-sheet
Notes:
This will also match `vx.y.zwhatever`, GH actions regex is limited and we can't use a proper regex for semver like in https://semver.org/
> Triggering builds on full semver tags

- controllers/limitador_controller.go
- pkg/helpers/helpers.go
- pkg/helpers/helpers_test.go
- pkg/limitador/k8s_objects.go
- pkg/limitador/k8s_objects_test.go
- pkg/reconcilers/deployment.go
Closes https://github.com/Kuadrant/limitador-operator/issues/176
- Checkout locally.
- Run `make run`
- `kubectl edit deployment`
- Add label to `spec.template.labels` something like `useradded: label`
- Verify that the deployment `spec.template.labels` includes the following labels
```
app: limitador
limitador-resource: limitador-sample
useradded: label
```
> do not overwrite user added labels added to the deployment template

- .github/workflows/build-images-for-tag-release.yaml
- RELEASE.md
- make/catalog.mk
Fixes #187 
Additionally: Fix channel used for custom catalogs. Aligned with the kuadrant operator: using `preview` for nightly/latest custom catalogs and `stable` for tagged releases.
> RELEASE.md: Verify OLM Deployment

- api/v1alpha1/limitador_types.go
- bundle/manifests/limitador-operator.clusterserviceversion.yaml
- bundle/manifests/limitador.kuadrant.io_limitadors.yaml
- charts/limitador-operator/templates/manifests.yaml
- config/crd/bases/limitador.kuadrant.io_limitadors.yaml
- controllers/limitador_controller.go
- controllers/limitador_controller_pdb_test.go
- pkg/limitador/k8s_objects.go
- pkg/limitador/k8s_objects_test.go
Added CEL validation for the pod disruption budget to the CRD definition. 
This gives the user faster feedback on poorly configured CRs, and the API will not allow the adding of the configuration.
Downside, the unit test needed to be replaced with an integration test.
> UPDATE: CRD validation

- Dockerfile
I ran into issues on a Kuadrant operator install for another component - details here: https://github.com/kagenti/mcp-gateway/issues/199. The limitadaor-operator install seems to come through the helm install of the kuadrant operator here: https://github.com/kagenti/mcp-gateway/blob/main/build/kuadrant.mk#L10
The errors suggested that despite my arm machine, an amd64 image was getting pulled. This was not resolved by separately pulling images via `docker pull --platform linux/arm64...`
```
runtime: lfstack.push invalid packing: node=0xffff5db7e800 cnt=0x1 packed=0xffff5db7e8000001 -> node=0xffffffff5db7e800
fatal error: lfstack.push
...
runtime.systemstack(0x47adff)
/usr/local/go/src/runtime/asm_amd64.s:509 +0x4a fp=0xffffa528f328 sp=0xffffa528f318 pc=0x4765ca
```
At this time, this seems …
> :fire: Remove goarch

- .github/workflows/build-images-base.yaml
https://github.com/Kuadrant/limitador-operator/pull/210 changed the behaviour of the naming of SHA images tags to a shortened value.
- https://quay.io/repository/kuadrant/limitador-operator?tab=tags&tag=latest
This PR restores the original behaviour of using the full SHA as the image tag
> fixup: use full SHA for image tag
